version: "3.3"
services:
  blog-server:
    build: ./micro-blogging-backend/
    image: blog-server-image:0.1
    container_name: blog-server
    ports:
      - "8082:8082"
    restart: always
    networks:
            micro_blog:
              ipv4_address: 172.19.0.4
    depends_on:
      - mysqldb
      
  blog-client:
    container_name: blog-client
    build: ./micro-blogging-frontend/
    image: blog-client-image:0.1
    ports:
      - "8085:8086"
    restart: always
    networks:
            micro_blog:
              ipv4_address: 172.19.0.3
    depends_on:
      - blog-server
 
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    networks:
            micro_blog:
              ipv4_address: 172.19.0.2
    environment:
        MYSQL_ROOT_PASSWORD: password 
        MYSQL_DATABASE: spring_test 
        MYSQL_USER: root 
        MYSQL_PASSWORD: password 
    volumes:
       - "./data:/var/lib/mysql" 

networks:
        micro_blog:
                driver: bridge  
                ipam:
                        driver: default
                        config:
                                - subnet: "172.19.0.0/16"